name: Deploy Node.js Backend → Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1 Checkout repo
      - uses: actions/checkout@v4

      # 2 Setup Node (use 20.x LTS)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json  # cache inside backend

      # 3 Install deps inside backend folder
      - name: Install dependencies
        working-directory: backend
        run: npm ci

      # 4 (Opt) Run tests or build scripts
      # - name: Run tests
      #   working-directory: backend
      #   run: npm test

      # 5 Zip the backend folder for deployment
      - name: Zip artifact
        run: |
          cd backend
          zip -r ../release.zip .

      # 6 Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: pallavi-auth0-backend                # <- your web app name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: release.zip
